name: Deploy to Plash

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Mask PLASH_SECRET
        run: echo "::add-mask::${{ secrets.PLASH_SECRET }}"

      - name: Create Plash config
        run: |
          mkdir -p ~/.config
          echo '${{ secrets.PLASH_SECRET }}' > ~/.config/plash_config.json

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install plash-cli with pip
        run: pip install plash-cli

  deploy-preview:
    needs: setup
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.pull_request.head.repo.full_name == github.repository || contains(github.event.pull_request.labels.*.name, 'preview-docs'))
    environment: 
        name: "Preview"
        url: https://rens-pr-${{ github.event.pull_request.number }}.plash.sh
    steps:
      - name: Deploy PR Preview
        run: bash ./deploy.sh "rens-pr-${{ github.event.pull_request.number }}"

  delete-preview:
    needs: setup
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed'
    environment: 
        name: "staging"
        url: https://rens-pr-${{ github.event.pull_request.number }}.plash.sh
    steps:
      - name: Delete PR Preview
        run: plash_delete --force --app_id "rens-pr-${{ github.event.pull_request.number }}"

  deploy-docs:
    needs: setup
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    environment: 
        name: "production"
        url: https://rensdimmnendaal.com
    steps:
      - name: Deploy Plash Docs
        run: bash ./deploy.sh